// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appendentry_request.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	appendentry_request.proto

It has these top-level messages:
	AppendEntriesReuqest
	AppendEntriesResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type AppendEntriesReuqest struct {
	Term          uint64      `protobuf:"varint,1,opt,name=Term" json:"Term,omitempty"`
	FirstLogIndex uint64      `protobuf:"varint,2,opt,name=FirstLogIndex" json:"FirstLogIndex,omitempty"`
	PreLogIndex   uint64      `protobuf:"varint,3,opt,name=PreLogIndex" json:"PreLogIndex,omitempty"`
	PreLogTerm    uint64      `protobuf:"varint,4,opt,name=PreLogTerm" json:"PreLogTerm,omitempty"`
	CommitIndex   uint64      `protobuf:"varint,5,opt,name=CommitIndex" json:"CommitIndex,omitempty"`
	LeaderName    string      `protobuf:"bytes,6,opt,name=LeaderName" json:"LeaderName,omitempty"`
	LeaderHost    string      `protobuf:"bytes,7,opt,name=LeaderHost" json:"LeaderHost,omitempty"`
	Entries       []*LogEntry `protobuf:"bytes,8,rep,name=Entries" json:"Entries,omitempty"`
}

func (m *AppendEntriesReuqest) Reset()                    { *m = AppendEntriesReuqest{} }
func (m *AppendEntriesReuqest) String() string            { return proto1.CompactTextString(m) }
func (*AppendEntriesReuqest) ProtoMessage()               {}
func (*AppendEntriesReuqest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *AppendEntriesReuqest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesReuqest) GetFirstLogIndex() uint64 {
	if m != nil {
		return m.FirstLogIndex
	}
	return 0
}

func (m *AppendEntriesReuqest) GetPreLogIndex() uint64 {
	if m != nil {
		return m.PreLogIndex
	}
	return 0
}

func (m *AppendEntriesReuqest) GetPreLogTerm() uint64 {
	if m != nil {
		return m.PreLogTerm
	}
	return 0
}

func (m *AppendEntriesReuqest) GetCommitIndex() uint64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func (m *AppendEntriesReuqest) GetLeaderName() string {
	if m != nil {
		return m.LeaderName
	}
	return ""
}

func (m *AppendEntriesReuqest) GetLeaderHost() string {
	if m != nil {
		return m.LeaderHost
	}
	return ""
}

func (m *AppendEntriesReuqest) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntriesResponse struct {
	Success     bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Term        uint64 `protobuf:"varint,2,opt,name=Term" json:"Term,omitempty"`
	Index       uint64 `protobuf:"varint,3,opt,name=Index" json:"Index,omitempty"`
	CommitIndex uint64 `protobuf:"varint,4,opt,name=CommitIndex" json:"CommitIndex,omitempty"`
}

func (m *AppendEntriesResponse) Reset()                    { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string            { return proto1.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()               {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntriesResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *AppendEntriesResponse) GetCommitIndex() uint64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func init() {
	proto1.RegisterType((*AppendEntriesReuqest)(nil), "proto.AppendEntriesReuqest")
	proto1.RegisterType((*AppendEntriesResponse)(nil), "proto.AppendEntriesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AppendEntries service

type AppendEntriesClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesReuqest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
}

type appendEntriesClient struct {
	cc *grpc.ClientConn
}

func NewAppendEntriesClient(cc *grpc.ClientConn) AppendEntriesClient {
	return &appendEntriesClient{cc}
}

func (c *appendEntriesClient) AppendEntries(ctx context.Context, in *AppendEntriesReuqest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := grpc.Invoke(ctx, "/proto.AppendEntries/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AppendEntries service

type AppendEntriesServer interface {
	AppendEntries(context.Context, *AppendEntriesReuqest) (*AppendEntriesResponse, error)
}

func RegisterAppendEntriesServer(s *grpc.Server, srv AppendEntriesServer) {
	s.RegisterService(&_AppendEntries_serviceDesc, srv)
}

func _AppendEntries_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesReuqest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppendEntriesServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AppendEntries/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppendEntriesServer).AppendEntries(ctx, req.(*AppendEntriesReuqest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppendEntries_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AppendEntries",
	HandlerType: (*AppendEntriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _AppendEntries_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appendentry_request.proto",
}

func init() { proto1.RegisterFile("appendentry_request.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0x87, 0x6d, 0xd7, 0xae, 0xf3, 0x8c, 0x31, 0x08, 0x13, 0xe2, 0x14, 0x29, 0xc5, 0x8b, 0x7a,
	0xb3, 0x8b, 0xf9, 0x04, 0x22, 0x8a, 0x42, 0x11, 0xa9, 0xde, 0xca, 0xa8, 0xeb, 0xa1, 0x14, 0x6c,
	0xd2, 0x25, 0x29, 0xb8, 0x0b, 0x9f, 0xc5, 0x57, 0x95, 0x26, 0x5b, 0xcd, 0xfe, 0x5c, 0xb5, 0xf9,
	0xbe, 0xd3, 0x73, 0x7a, 0x7e, 0x81, 0xf3, 0xac, 0xae, 0x91, 0xe5, 0xc8, 0x94, 0x58, 0x2f, 0x04,
	0xae, 0x1a, 0x94, 0x6a, 0x56, 0x0b, 0xae, 0x38, 0xf1, 0xf5, 0x63, 0x3a, 0xfe, 0xe2, 0xc5, 0x42,
	0x7b, 0xc3, 0xa3, 0x5f, 0x17, 0x26, 0x77, 0xfa, 0xab, 0x07, 0xa6, 0x44, 0x89, 0x32, 0xc5, 0x66,
	0x85, 0x52, 0x11, 0x02, 0xde, 0x3b, 0x8a, 0x8a, 0x3a, 0xa1, 0x13, 0x7b, 0xa9, 0x7e, 0x27, 0xd7,
	0x30, 0x7a, 0x2c, 0x85, 0x54, 0x09, 0x2f, 0x9e, 0x59, 0x8e, 0xdf, 0xd4, 0xd5, 0x72, 0x17, 0x92,
	0x10, 0x86, 0xaf, 0x02, 0xbb, 0x9a, 0x9e, 0xae, 0xb1, 0x11, 0xb9, 0x02, 0x30, 0x47, 0x3d, 0xc1,
	0xd3, 0x05, 0x16, 0x69, 0x3b, 0xdc, 0xf3, 0xaa, 0x2a, 0x95, 0xe9, 0xe0, 0x9b, 0x0e, 0x16, 0x6a,
	0x3b, 0x24, 0x98, 0xe5, 0x28, 0x5e, 0xb2, 0x0a, 0x69, 0x3f, 0x74, 0xe2, 0xd3, 0xd4, 0x22, 0xff,
	0xfe, 0x89, 0x4b, 0x45, 0x03, 0xdb, 0xb7, 0x84, 0xdc, 0x40, 0xb0, 0xd9, 0x97, 0x0e, 0xc2, 0x5e,
	0x3c, 0x9c, 0x8f, 0x4d, 0x1e, 0xb3, 0x84, 0x17, 0xad, 0x58, 0xa7, 0x5b, 0x1f, 0xfd, 0xc0, 0xd9,
	0x5e, 0x40, 0xb2, 0xe6, 0x4c, 0x22, 0xa1, 0x10, 0xbc, 0x35, 0xcb, 0x25, 0x4a, 0xa9, 0x43, 0x1a,
	0xa4, 0xdb, 0x63, 0x97, 0x9d, 0x6b, 0x65, 0x37, 0x01, 0xdf, 0xce, 0xc3, 0xef, 0xb2, 0xb2, 0x37,
	0xf5, 0x0e, 0x36, 0x9d, 0x7f, 0xc0, 0x68, 0x67, 0x3c, 0x49, 0xf6, 0xc1, 0xc5, 0xe6, 0xd7, 0x8f,
	0x5d, 0xe3, 0xf4, 0xf2, 0xb8, 0x34, 0x2b, 0x44, 0x27, 0x9f, 0x7d, 0xad, 0x6f, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xae, 0x7a, 0xcf, 0x7d, 0x3b, 0x02, 0x00, 0x00,
}
