// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vote_request.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	vote_request.proto

It has these top-level messages:
	VoteRequest
	VoteResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type VoteRequest struct {
	Term          uint64 `protobuf:"varint,1,opt,name=Term" json:"Term,omitempty"`
	LastLogIndex  uint64 `protobuf:"varint,2,opt,name=LastLogIndex" json:"LastLogIndex,omitempty"`
	LastLogTerm   uint64 `protobuf:"varint,3,opt,name=LastLogTerm" json:"LastLogTerm,omitempty"`
	CandidateName string `protobuf:"bytes,4,opt,name=CandidateName" json:"CandidateName,omitempty"`
}

func (m *VoteRequest) Reset()                    { *m = VoteRequest{} }
func (m *VoteRequest) String() string            { return proto1.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()               {}
func (*VoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VoteRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteRequest) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *VoteRequest) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *VoteRequest) GetCandidateName() string {
	if m != nil {
		return m.CandidateName
	}
	return ""
}

type VoteResponse struct {
	Term        uint64 `protobuf:"varint,1,opt,name=Term" json:"Term,omitempty"`
	VoteGranted bool   `protobuf:"varint,2,opt,name=VoteGranted" json:"VoteGranted,omitempty"`
}

func (m *VoteResponse) Reset()                    { *m = VoteResponse{} }
func (m *VoteResponse) String() string            { return proto1.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()               {}
func (*VoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VoteResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

func init() {
	proto1.RegisterType((*VoteRequest)(nil), "proto.VoteRequest")
	proto1.RegisterType((*VoteResponse)(nil), "proto.VoteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RequestVote service

type RequestVoteClient interface {
	RequestVoteMe(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
}

type requestVoteClient struct {
	cc *grpc.ClientConn
}

func NewRequestVoteClient(cc *grpc.ClientConn) RequestVoteClient {
	return &requestVoteClient{cc}
}

func (c *requestVoteClient) RequestVoteMe(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	out := new(VoteResponse)
	err := grpc.Invoke(ctx, "/proto.RequestVote/RequestVoteMe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RequestVote service

type RequestVoteServer interface {
	RequestVoteMe(context.Context, *VoteRequest) (*VoteResponse, error)
}

func RegisterRequestVoteServer(s *grpc.Server, srv RequestVoteServer) {
	s.RegisterService(&_RequestVote_serviceDesc, srv)
}

func _RequestVote_RequestVoteMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestVoteServer).RequestVoteMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RequestVote/RequestVoteMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestVoteServer).RequestVoteMe(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RequestVote_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RequestVote",
	HandlerType: (*RequestVoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVoteMe",
			Handler:    _RequestVote_RequestVoteMe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vote_request.proto",
}

func init() { proto1.RegisterFile("vote_request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0xcb, 0x2f, 0x49,
	0x8d, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x05, 0x53, 0x4a, 0xbd, 0x8c, 0x5c, 0xdc, 0x61, 0xf9, 0x25, 0xa9, 0x41, 0x10, 0x49, 0x21, 0x21,
	0x2e, 0x96, 0x90, 0xd4, 0xa2, 0x5c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x30, 0x5b, 0x48,
	0x89, 0x8b, 0xc7, 0x27, 0xb1, 0xb8, 0xc4, 0x27, 0x3f, 0xdd, 0x33, 0x2f, 0x25, 0xb5, 0x42, 0x82,
	0x09, 0x2c, 0x87, 0x22, 0x26, 0xa4, 0xc0, 0xc5, 0x0d, 0xe5, 0x83, 0xb5, 0x33, 0x83, 0x95, 0x20,
	0x0b, 0x09, 0xa9, 0x70, 0xf1, 0x3a, 0x27, 0xe6, 0xa5, 0x64, 0xa6, 0x24, 0x96, 0xa4, 0xfa, 0x25,
	0xe6, 0xa6, 0x4a, 0xb0, 0x28, 0x30, 0x6a, 0x70, 0x06, 0xa1, 0x0a, 0x2a, 0xb9, 0x70, 0xf1, 0x40,
	0x9c, 0x53, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x8a, 0xd5, 0x3d, 0x0a, 0x10, 0x27, 0xbb, 0x17, 0x25,
	0xe6, 0x95, 0xa4, 0xa6, 0x80, 0x9d, 0xc3, 0x11, 0x84, 0x2c, 0x64, 0xe4, 0xc9, 0xc5, 0x0d, 0xf5,
	0x10, 0x48, 0x54, 0xc8, 0x8a, 0x8b, 0x17, 0x89, 0xeb, 0x9b, 0x2a, 0x24, 0x04, 0x09, 0x04, 0x3d,
	0x24, 0x9f, 0x4b, 0x09, 0xa3, 0x88, 0x41, 0xac, 0x57, 0x62, 0x48, 0x62, 0x03, 0x8b, 0x1a, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xf1, 0xb6, 0x4b, 0x44, 0x01, 0x00, 0x00,
}
